# Assignment_1: Data Pre Processing using Functions in Python:

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

df = pd.read_csv("ipl_data.csv")
df.head()

,match_id,team,opponent,venue,player_role,runs_scored,balls_faced,strike_rate,wickets,economy,age,match_result,commentary
0,1,PBKS,RCB,Chinnaswamy,NaN,38.0,20.0,52.71,1.0,8.98,28.0,Win,Spin bowlers turned the game around in the mid...
1,2,KKR,CSK,Chepauk,Wicket-Keeper,1.0,59.0,124.08,0.0,4.68,NaN,Win,Spin bowlers turned the game around in the mid...
2,3,RR,KKR,Wankhede,Wicket-Keeper,2.0,36.0,76.82,0.0,4.41,19.0,Tie,"The crowd was electric tonight, great atmosphere."
3,4,SRH,MI,Feroz Shah Kotla,Bowler,112.0,19.0,NaN,0.0,8.25,23.0,Win,Spin bowlers turned the game around in the mid...
4,5,PBKS,RR,Narendra Modi Stadium,Bowler,100.0,67.0,161.63,2.0,8.33,31.0,Tie,Amazing fielding efforts saved many runs today.

In [2]:
df.isnull().sum()

match_id        0
team            0
opponent        0
venue           3
player_role     4
runs_scored     4
balls_faced     0
strike_rate     5
wickets         0
economy         0
age             4
match_result    0
commentary      4
dtype: int64

# for NUMERICAL VALUES -  replace by mean

In [8]:
def heart_killers(data):
    num_cols = data.select_dtypes(include=['int64', 'float64']).columns

    for col in num_cols:
        data[col] = data[col].fillna(data[col].mean())

    return data

# for CATEGORICAL VALUES - replace by mode

In [9]:
def double_helix(data):
    cat_cols = data.select_dtypes(include=['object', 'string']).columns

    for col in cat_cols:
        data[col] = data[col].fillna(data[col].mode()[0])

    return data

In [10]:
df = heart_killers(df)
df = double_helix(df)

In [11]:
df.isnull().sum()

match_id        0
team            0
opponent        0
venue           0
player_role     0
runs_scored     0
balls_faced     0
strike_rate     0
wickets         0
economy         0
age             0
match_result    0
commentary      0
dtype: int64

In [12]:
df

,match_id,team,opponent,venue,player_role,runs_scored,balls_faced,strike_rate,wickets,economy,age,match_result,commentary
0,1,PBKS,RCB,Chinnaswamy,Batsman,38.00000,20.0,52.710000,1.0,8.98,28.000000,Win,Spin bowlers turned the game around in the mid...
1,2,KKR,CSK,Chepauk,Wicket-Keeper,1.00000,59.0,124.080000,0.0,4.68,28.043478,Win,Spin bowlers turned the game around in the mid...
2,3,RR,KKR,Wankhede,Wicket-Keeper,2.00000,36.0,76.820000,0.0,4.41,19.000000,Tie,"The crowd was electric tonight, great atmosphere."
3,4,SRH,MI,Feroz Shah Kotla,Bowler,112.00000,19.0,127.137556,0.0,8.25,23.000000,Win,Spin bowlers turned the game around in the mid...
4,5,PBKS,RR,Narendra Modi Stadium,Bowler,100.00000,67.0,161.630000,2.0,8.33,31.000000,Tie,Amazing fielding efforts saved many runs today.
5,6,LSG,KKR,Eden Gardens,All-Rounder,112.00000,19.0,158.140000,5.0,9.10,22.000000,Loss,Brilliant bowling performance!! Bowlers domina...
6,7,RCB,MI,Chinnaswamy,Wicket-Keeper,55.00000,20.0,96.210000,4.0,9.81,28.043478,Win,"The crowd was electric tonight, great atmosphere."
7,8,PBKS,DC,Feroz Shah Kotla,Bowler,80.00000,71.0,131.380000,1.0,11.81,34.000000,Tie,Poor batting display from the top order today :(
8,9,RR,DC,Eden Gardens,All-Rounder,58.00000,52.0,126.320000,1.0,8.13,20.000000,Tie,Spin bowlers turned the game around in the mid...
9,10,SRH,LSG,Eden Gardens,Wicket-Keeper,112.00000,33.0,145.450000,2.0,6.58,35.000000,Loss,Spin bowlers turned the game around in the mid...
10,11,KKR,KKR,Wankhede,Batsman,1.00000,40.0,87.570000,1.0,10.36,38.000000,Win,Spin bowlers turned the game around in the mid...
11,12,RR,DC,Eden Gardens,Batsman,1.00000,39.0,138.480000,0.0,6.17,30.000000,Win,What a fantastic match! Thrilling finish to th...
12,13,RR,MI,Narendra Modi Stadium,Bowler,91.00000,1.0,196.830000,4.0,7.51,36.000000,Tie,Captain's decision to bat first was a blunder!!!
13,14,RCB,LSG,Feroz Shah Kotla,Batsman,53.00000,11.0,127.137556,3.0,4.63,21.000000,Win,"The crowd was electric tonight, great atmosphere."
14,15,DC,MI,Eden Gardens,Batsman,86.00000,57.0,185.910000,1.0,4.20,19.000000,Tie,"Rain interrupted play twice, frustrating for f..."
15,16,SRH,LSG,Wankhede,Batsman,100.00000,50.0,127.137556,0.0,11.70,19.000000,Win,Spin bowlers turned the game around in the mid...
16,17,MI,KKR,Narendra Modi Stadium,All-Rounder,95.00000,23.0,102.510000,3.0,10.69,37.000000,Tie,Spin bowlers turned the game around in the mid...
17,18,RR,RR,Chepauk,Bowler,96.00000,31.0,146.770000,4.0,9.57,29.000000,Win,Poor batting display from the top order today :(
18,19,DC,PBKS,Feroz Shah Kotla,Batsman,0.00000,42.0,150.340000,3.0,7.27,23.000000,Loss,Spin bowlers turned the game around in the mid...
19,20,MI,GT,Eden Gardens,Wicket-Keeper,18.00000,7.0,179.630000,0.0,5.39,30.000000,Win,Poor batting display from the top order today :(
20,21,SRH,RR,Wankhede,Batsman,1.00000,16.0,84.530000,5.0,5.25,21.000000,Win,Amazing fielding efforts saved many runs today.
21,22,CSK,SRH,Chepauk,Batsman,52.00000,60.0,124.880000,5.0,6.00,19.000000,Loss,Amazing fielding efforts saved many runs today.
22,23,LSG,MI,Narendra Modi Stadium,All-Rounder,62.26087,2.0,135.800000,3.0,8.39,19.000000,Win,Captain's decision to bat first was a blunder!!!
23,24,DC,SRH,Narendra Modi Stadium,All-Rounder,89.00000,1.0,165.280000,2.0,9.72,26.000000,Loss,Brilliant bowling performance!! Bowlers domina...
24,25,GT,RR,Narendra Modi Stadium,Bowler,31.00000,48.0,56.540000,3.0,9.28,28.000000,Win,"Rain interrupted play twice, frustrating for f..."
25,26,CSK,LSG,Eden Gardens,Batsman,69.00000,12.0,199.180000,1.0,6.24,28.043478,Tie,What a fantastic match! Thrilling finish to th...
26,27,LSG,GT,Wankhede,All-Rounder,62.26087,69.0,120.490000,1.0,11.64,30.000000,Tie,Captain's decision to bat first was a blunder!!!
27,28,RCB,GT,Chinnaswamy,Batsman,118.00000,37.0,91.930000,5.0,9.90,31.000000,Win,"Average match, nothing special to write about."
28,29,PBKS,CSK,Narendra Modi Stadium,Bowler,67.00000,32.0,182.520000,2.0,8.43,30.000000,Win,What a fantastic match! Thrilling finish to th...
29,30,KKR,GT,Chinnaswamy,Batsman,54.00000,9.0,162.160000,0.0,8.89,32.000000,Win,"The crowd was electric tonight, great atmosphere."
30,31,GT,PBKS,Feroz Shah Kotla,Batsman,74.00000,19.0,192.960000,1.0,7.36,28.043478,Tie,Spin bowlers turned the game around in the mid...
31,32,RCB,GT,Narendra Modi Stadium,All-Rounder,55.00000,48.0,99.610000,5.0,5.98,37.000000,Win,"Average match, nothing special to write about."
32,33,SRH,RR,Narendra Modi Stadium,Bowler,16.00000,3.0,132.910000,4.0,6.85,36.000000,Tie,"Average match, nothing special to write about."
33,34,RCB,CSK,Eden Gardens,Wicket-Keeper,37.00000,20.0,127.137556,5.0,10.06,21.000000,Loss,Captain's decision to bat first was a blunder!!!
34,35,PBKS,RR,Narendra Modi Stadium,Wicket-Keeper,23.00000,24.0,197.050000,1.0,4.12,35.000000,Tie,Brilliant bowling performance!! Bowlers domina...
35,36,SRH,RR,Chinnaswamy,All-Rounder,68.00000,54.0,61.300000,1.0,4.93,26.000000,Tie,Captain's decision to bat first was a blunder!!!
36,37,GT,RCB,Narendra Modi Stadium,All-Rounder,115.00000,33.0,95.850000,5.0,4.37,28.000000,Loss,"The crowd was electric tonight, great atmosphere."
37,38,PBKS,CSK,Eden Gardens,Bowler,97.00000,24.0,78.640000,0.0,4.33,20.000000,Tie,Spin bowlers turned the game around in the mid...
38,39,MI,RR,Eden Gardens,Batsman,69.00000,75.0,90.270000,3.0,10.84,37.000000,Win,Spin bowlers turned the game around in the mid...
39,40,KKR,RCB,Feroz Shah Kotla,Wicket-Keeper,85.00000,72.0,122.790000,1.0,9.63,27.000000,Win,Brilliant bowling performance!! Bowlers domina...
40,41,GT,RCB,Chinnaswamy,Wicket-Keeper,10.00000,36.0,105.900000,5.0,7.79,25.000000,Tie,"The crowd was electric tonight, great atmosphere."
41,42,MI,CSK,Chepauk,Batsman,111.00000,38.0,109.200000,5.0,4.78,22.000000,Win,Brilliant bowling performance!! Bowlers domina...
42,43,LSG,SRH,Chepauk,Wicket-Keeper,15.00000,25.0,176.630000,2.0,7.93,39.000000,Tie,Poor batting display from the top order today :(
43,44,GT,LSG,Narendra Modi Stadium,Batsman,96.00000,18.0,189.500000,3.0,7.79,36.000000,Win,Spin bowlers turned the game around in the mid...
44,45,LSG,PBKS,Feroz Shah Kotla,Bowler,72.00000,66.0,60.560000,4.0,5.39,31.000000,Win,"Average match, nothing special to write about."
45,46,SRH,LSG,Wankhede,Batsman,58.00000,54.0,81.340000,0.0,7.47,29.000000,Tie,"Rain interrupted play twice, frustrating for f..."
46,47,MI,GT,Narendra Modi Stadium,Bowler,62.26087,35.0,150.670000,4.0,7.19,22.000000,Win,Spin bowlers turned the game around in the mid...
47,48,KKR,PBKS,Narendra Modi Stadium,Wicket-Keeper,79.00000,61.0,103.800000,3.0,8.93,39.000000,Tie,"The crowd was electric tonight, great atmosphere."
48,49,PBKS,GT,Chinnaswamy,Wicket-Keeper,92.00000,41.0,88.120000,3.0,9.08,22.000000,Win,What a fantastic match! Thrilling finish to th...
49,50,RR,RR,Chinnaswamy,Bowler,62.26087,33.0,127.137556,3.0,4.36,28.000000,Win,Brilliant bowling performance!! Bowlers domina...